
#              SİGMOİD
#    0 İLE 1 ARASINDA DEĞER ALIR
#    GENELDE SINIFLANDIRMA PROBLEMLERİNDE KULLANILIR

#            TANH(HİPERBOLİK TANJANT)
#    -1 İLE 1 ARASINDA DEĞER ALIR
#    NEGATİF DEĞERLERLE DAHA GENİŞ BİR KAPSAM SAĞLAR VE GENELDE SINIFLANDIRMA OPERASYONLARINDA KULLANILIR

#           RELU(RECTİFİED LİNEAR UNİT)  
#    0 İLE SONSUZ ARASIDNA DEĞER ALIR
#    DERİN ÖĞRENME ALANINDA SIKLIKLA KARŞIMIZA ÇIKAR

#           LİNEAR FONKSİYONLAR
#    F(X)=X
#    SONSUZ DEĞER ALABİLİR FAKAT NON-LİNEAR OLMAMASI SEBEBİYLE MODELLERDE SORUNLARA YOL AÇABİLİR

      
   